// <auto-generated />
using System;
using MarkStickyNotes.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarkStickyNotes.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260704092610_AddIsDeletedToStatus")]
    partial class AddIsDeletedToStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("MarkStickyNotes.Entities.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorCode = "#D7AD04",
                            Name = "Yellow",
                            Order = 1
                        },
                        new
                        {
                            Id = 2,
                            ColorCode = "#6FD262",
                            Name = "Green",
                            Order = 2
                        },
                        new
                        {
                            Id = 3,
                            ColorCode = "#EA86C2",
                            Name = "Pink",
                            Order = 3
                        },
                        new
                        {
                            Id = 4,
                            ColorCode = "#C78EFF",
                            Name = "Purple",
                            Order = 4
                        },
                        new
                        {
                            Id = 5,
                            ColorCode = "#5AC0E7",
                            Name = "Blue",
                            Order = 5
                        },
                        new
                        {
                            Id = 6,
                            ColorCode = "#AAAAAA",
                            Name = "Gray",
                            Order = 6
                        },
                        new
                        {
                            Id = 7,
                            ColorCode = "#4E4E4E",
                            Name = "DarkGray",
                            Order = 7
                        });
                });

            modelBuilder.Entity("MarkStickyNotes.Entities.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("MarkStickyNotes.Entities.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "未対応",
                            Order = 1
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "処理中",
                            Order = 2
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "処理済み",
                            Order = 3
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "完了",
                            Order = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
